### ISSUE TITLE
count_columns always returns 100 when # columns > 100

### ISSUE THREAD

**Issue by elzoiddy** [cassandra-rb/cassandra#100] opened 2011-07-28 00:43 UTC
May be this has already been discussed.  Seems there is no way to get the total column count with count_columns when the number of columns is greater than 100 in a row.  Is this by design? or a defect?

Thanks

``` ruby
require 'rubygems'
require 'cassandra/0.8'

cassandra = Cassandra.new("Keyspace1", "localhost:9160")
columns = (1..200).inject({}){|h, v| h[v.to_s] = v.to_s; h }
p columns.keys.size

cassandra.insert("opportunity_buckets", "my_key", columns)
p cassandra.count_columns("opportunity_buckets", "my_key")

=> 100
```

in the cassandra-cli the count returns correctly. 

```
[default@Keyspace1] count opportunity_buckets['my_key'];
200 columns
```

**Comment by ryanking** [comment] 2011-07-28 16:18
A defect.

**Comment by rwjblue** [comment] 2011-07-29 12:29
Agreed.  I'll start working on it.

**Comment by rwjblue** [comment] 2011-08-06 21:17
The issue is that Cassandra's SliceRange defaults to 100 columns.  I think the best thing to do is to allow a new param for :count that will let you specify the maximum count of columns.  That way the current behavior still preserves resources, but we have the ability to get any arbitrary count if we need to count more than 100.

**Comment by rwjblue** [comment] 2011-08-06 21:34
Just pushed a fix for this issue along with some extra testing to verify the behavior.

**Closed as completed by rwjblue** 2011-08-06 21:34 UTC

**Comment by elzoiddy** [comment] 2011-08-06 22:37
What is the recommended way to get the total count of columns from a row? By setting the max count to max int32 value?

Is there any plans make it like the cassandra get_count call?  
i32 get_count(key, column_parent, predicate, consistency_level)

**Comment by rwjblue** [comment] 2011-08-06 22:56
The current behavior is like the get_count call (as I understand it). 

When calling get_count on cassandra itself the SliceRange parameter defaults to 100 columns [1]. If you need more to count more than 100 you need to explicitly pass the count param when building the SliceRange. 

The count_columns method works the same way. I am definitely open to suggestions. 

[1] https://github.com/apache/cassandra/blob/trunk/interface/cassandra.thrift

**Comment by elzoiddy** [comment] 2011-08-08 17:09
Ok, great. Thanks for fixing it.
