### ISSUE TITLE
When I use the conn.get_columns(:CF, "key"), It throws the Exception

### ISSUE THREAD

**Issue by floys** [cassandra-rb/cassandra#18] opened 2010-04-03 15:23 UTC
the keySpace is Examine
the CF is <ColumnFamily Name="Ranks" CompareWith="UTF8Type"/>
I have doing:
  conn.insert(:Ranks, "tmprank", {"1" => ... , "2"=>... "3" => ....})
  conn.get_columns(:Ranks, "tmprank")
It throw

CassandraThrift::InvalidRequestException: CassandraThrift::InvalidRequestException
    from /opt/ruby/lib/ruby/gems/1.8/gems/cassandra-0.8.1/lib/../vendor/gen-rb/cassandra.rb:62:in `recv_get_slice'
    from /opt/ruby/lib/ruby/gems/1.8/gems/cassandra-0.8.1/lib/../vendor/gen-rb/cassandra.rb:52:in`get_slice'
    from /opt/ruby/lib/ruby/gems/1.8/gems/thrift_client-0.4.1/lib/thrift_client/abstract_thrift_client.rb:60:in `send'
    from /opt/ruby/lib/ruby/gems/1.8/gems/thrift_client-0.4.1/lib/thrift_client/abstract_thrift_client.rb:60:in`send_rpc'
    from /opt/ruby/lib/ruby/gems/1.8/gems/thrift_client-0.4.1/lib/thrift_client/abstract_thrift_client.rb:156:in `send_rpc'
    from /opt/ruby/lib/ruby/gems/1.8/gems/thrift_client-0.4.1/lib/thrift_client/abstract_thrift_client.rb:56:in`proxy'
    from /opt/ruby/lib/ruby/gems/1.8/gems/thrift_client-0.4.1/lib/thrift_client/abstract_thrift_client.rb:146:in `proxy'
    from /opt/ruby/lib/ruby/gems/1.8/gems/thrift_client-0.4.1/lib/thrift_client/abstract_thrift_client.rb:49:in`handled_proxy'
    from /opt/ruby/lib/ruby/gems/1.8/gems/thrift_client-0.4.1/lib/thrift_client/abstract_thrift_client.rb:142:in `handled_proxy'
    from /opt/ruby/lib/ruby/gems/1.8/gems/thrift_client-0.4.1/lib/thrift_client/abstract_thrift_client.rb:23:in`get_slice'
    from /opt/ruby/lib/ruby/gems/1.8/gems/cassandra-0.8.1/lib/cassandra/protocol.rb:30:in `_get_columns'
    from /opt/ruby/lib/ruby/gems/1.8/gems/cassandra-0.8.1/lib/cassandra/cassandra.rb:175:in`get_columns'
    from (irb):16

my env is 
cassandra server 0.6 rc1
ruby gems
cassandra 0.8.1
thrift 0.2.0
thrift_client 0.4.1
And How can I get_range to get keys with LongType?
When I set it to LongType
I get_range will be []
But touch the cassandra, I feel good.
Thx to this lib.

**Comment by ryanking** [comment] 2010-04-08 00:18
can you post your storage-conf entry for the CF in question?

**Comment by ryanking** [comment] 2010-04-20 00:27
can't reproduce, so closing this for now. reopen if you can give us more info to reproduce.

**Closed as completed by ryanking** 2010-04-20 00:27 UTC

**Comment by burt** [comment] 2010-06-08 11:35
Hi,

I'm having the same issue trying to retrieve all columns for a row. Gem version is cassandra (0.8.2) and cassandra 0.6.2.

My keyspace looks like this:

```
<Keyspace Name="Cache">
  <ColumnFamily 
Name="Entries"
CompareWith="UTF8Type"
ColumnType="Super"
CompareSubcolumnsWith="UTF8Type" />
  <ReplicaPlacementStrategy>org.apache.cassandra.locator.RackUnawareStrategy</ReplicaPlacementStrategy>
  <ReplicationFactor>1</ReplicationFactor>
  <EndPointSnitch>org.apache.cassandra.locator.EndPointSnitch</EndPointSnitch>
</Keyspace>
```

Any ideas?
Thanks,
f

**Comment by ghost** [comment] 2010-06-08 18:17
Same problem here.  Gem 0.8.2, Cassandra 0.6.0-RC1

Keyspace:

```
<Keyspace Name="gf">
    <ColumnFamily Name="position_messages"
                ColumnType="Super"
                CompareWith="LongType"
                CompareSubcolumnsWith="UTF8Type" />
 <ReplicaPlacementStrategy>org.apache.cassandra.locator.RackUnawareStrategy</ReplicaPlacementStrategy>
  <ReplicationFactor>1</ReplicationFactor>
  <EndPointSnitch>org.apache.cassandra.locator.EndPointSnitch</EndPointSnitch>
</Keyspace>
```

Sample request code:

```
c.get_columns 'position_messages', '230005'
```

Error:

```
CassandraThrift::InvalidRequestException: CassandraThrift::InvalidRequestException
from /Library/Ruby/Gems/1.8/gems/cassandra-0.8.2/lib/../vendor/gen-rb/cassandra.rb:62:in `recv_get_slice'
from /Library/Ruby/Gems/1.8/gems/cassandra-0.8.2/lib/../vendor/gen-rb/cassandra.rb:52:in `get_slice'
from /Library/Ruby/Gems/1.8/gems/thrift_client-0.4.2/lib/thrift_client/abstract_thrift_client.rb:64:in `send'
from /Library/Ruby/Gems/1.8/gems/thrift_client-0.4.2/lib/thrift_client/abstract_thrift_client.rb:64:in `send_rpc'
from /Library/Ruby/Gems/1.8/gems/thrift_client-0.4.2/lib/thrift_client/abstract_thrift_client.rb:161:in `send_rpc'
from /Library/Ruby/Gems/1.8/gems/thrift_client-0.4.2/lib/thrift_client/abstract_thrift_client.rb:60:in `proxy'
from /Library/Ruby/Gems/1.8/gems/thrift_client-0.4.2/lib/thrift_client/abstract_thrift_client.rb:151:in `proxy'
from /Library/Ruby/Gems/1.8/gems/thrift_client-0.4.2/lib/thrift_client/abstract_thrift_client.rb:53:in `handled_proxy'
from /Library/Ruby/Gems/1.8/gems/thrift_client-0.4.2/lib/thrift_client/abstract_thrift_client.rb:147:in `handled_proxy'
from /Library/Ruby/Gems/1.8/gems/thrift_client-0.4.2/lib/thrift_client/abstract_thrift_client.rb:23:in `get_slice'
from /Library/Ruby/Gems/1.8/gems/cassandra-0.8.2/lib/cassandra/protocol.rb:30:in `_get_columns'
from /Library/Ruby/Gems/1.8/gems/cassandra-0.8.2/lib/cassandra/cassandra.rb:180:in `get_columns'
from (irb):81
from :0
```

**Comment by ghost** [comment] 2010-06-08 18:18
Hmm... this issue is closed.  Can someone re-open?

**Comment by BilalAhmed** [comment] 2011-06-04 01:58
Was this ever resolved?

I am also getting an error while running client.get_columns(:Categories,"01")

CassandraThrift::InvalidRequestException: CassandraThrift::InvalidRequestException
    from /Users/bilal/.rvm/gems/ruby-1.9.2-p180-tawkoo/gems/cassandra-0.11.1/vendor/0.7/gen-rb/cassandra.rb:78:in `recv_get_slice'
    from /Users/bilal/.rvm/gems/ruby-1.9.2-p180-tawkoo/gems/cassandra-0.11.1/vendor/0.7/gen-rb/cassandra.rb:68:in`get_slice'
    from /Users/bilal/.rvm/gems/ruby-1.9.2-p180-tawkoo/gems/thrift_client-0.6.2/lib/thrift_client/abstract_thrift_client.rb:116:in `handled_proxy'
    from /Users/bilal/.rvm/gems/ruby-1.9.2-p180-tawkoo/gems/thrift_client-0.6.2/lib/thrift_client/abstract_thrift_client.rb:58:in`get_slice'
    from /Users/bilal/.rvm/gems/ruby-1.9.2-p180-tawkoo/gems/cassandra-0.11.1/lib/cassandra/protocol.rb:36:in `_get_columns'
    from /Users/bilal/.rvm/gems/ruby-1.9.2-p180-tawkoo/gems/cassandra-0.11.1/lib/cassandra/cassandra.rb:533:in`get_columns'
    from (irb):72
    from /Users/bilal/.rvm/rubies/ruby-1.9.2-p180-tawkoo/bin/irb:16:in `<main>'

Here is the definition of column family:

create column family Categories
 with column_type = 'Super'
 and comparator = UTF8Type
 and subcomparator = UTF8Type; 

Environment:
Cassandra server 0.8
cassandra 0.11.1
