### ISSUE TITLE
Abort trap: 6

### ISSUE THREAD

**Issue by adilsoncarvalho** [cassandra-rb/cassandra#109] opened 2011-08-10 01:26 UTC
Hi,

Just installed Cassandra on my Mac OS Lion and created that [Twissandra example](http://wiki.apache.org/cassandra/CassandraCli) from Cassandra's wiki page. All worked perfectly.

After I installed cassandra gem I've wrote a simple app to insert one new key into User, but it always stops displaying the message `Abort trap: 6`

I am using Ruby 1.9.2 with RVM and Cassandra is 0.8.3.

The source code I've wrote is:

``` ruby
require 'cassandra'
db = Cassandra.new 'Twissandra' # pointing to localhost
db.insert(:User, 'acarvalho', { 'first' => 'Adilson', 'last' => 'Carvalho', 'age' => 34 })
```

The column is declared as:

```
[default@Twissandra] update column family User with
... column_metadata = 
... [
... {column_name: first, validation_class: UTF8Type},
... {column_name: last, validation_class: UTF8Type},
... {column_name: age, validation_class: UTF8Type, index_type: KEYS}
... ];
```

**Comment by rwjblue** [comment] 2011-08-10 01:58
FYI - I am running on OS X Lion under 1.9.2p290 without issue (using gcc-4.2 not LLVM).  All tests pass.

Can you try running under 1.8.7?

Take a look at: 
http://redmine.ruby-lang.org/issues/5003

It may be an issue with llvm-gcc compile optimizations.  Could you try:

```
export CC=gcc-4.2
rvm remove 1.9.2 && rvm install 1.9.2
```

**Comment by adilsoncarvalho** [comment] 2011-08-10 11:59
Hi,

I've tried using 1.8.7, but at first it could not locate cassandra gem, so I had to add a require to rubygems prior to the cassandra's one.

When I run the code it throws the following error:

```
$ ruby cassandra 
/usr/local/rvm/gems/ruby-1.8.7-p334/gems/cassandra-0.11.4/lib/../vendor/0.7/gen-rb/cassandra_types.rb:672:in `validate': Required field replication_factor is unset! (Thrift::ProtocolException)
    from /usr/local/rvm/gems/ruby-1.8.7-p334/gems/thrift-0.6.0/lib/thrift/client.rb:48:in `read'
    from /usr/local/rvm/gems/ruby-1.8.7-p334/gems/thrift-0.6.0/lib/thrift/client.rb:48:in `receive_message'
    from /usr/local/rvm/gems/ruby-1.8.7-p334/gems/cassandra-0.11.4/lib/../vendor/0.7/gen-rb/cassandra.rb:359:in `recv_describe_keyspace'
    from /usr/local/rvm/gems/ruby-1.8.7-p334/gems/cassandra-0.11.4/lib/../vendor/0.7/gen-rb/cassandra.rb:351:in `describe_keyspace'
    from /usr/local/rvm/gems/ruby-1.8.7-p334/gems/thrift_client-0.6.3/lib/thrift_client/abstract_thrift_client.rb:130:in `send'
    from /usr/local/rvm/gems/ruby-1.8.7-p334/gems/thrift_client-0.6.3/lib/thrift_client/abstract_thrift_client.rb:130:in `handled_proxy'
    from /usr/local/rvm/gems/ruby-1.8.7-p334/gems/thrift_client-0.6.3/lib/thrift_client/abstract_thrift_client.rb:59:in `describe_keyspace'
    from /usr/local/rvm/gems/ruby-1.8.7-p334/gems/cassandra-0.11.4/lib/cassandra/cassandra.rb:168:in `schema'
    from /usr/local/rvm/gems/ruby-1.8.7-p334/gems/cassandra-0.11.4/lib/cassandra/columns.rb:31:in `column_family_property'
    from /usr/local/rvm/gems/ruby-1.8.7-p334/gems/cassandra-0.11.4/lib/cassandra/columns.rb:20:in `column_name_class_for_key'
    from /usr/local/rvm/gems/ruby-1.8.7-p334/gems/cassandra-0.11.4/lib/cassandra/columns.rb:12:in `column_name_class'
    from /usr/local/rvm/gems/ruby-1.8.7-p334/gems/cassandra-0.11.4/lib/cassandra/helpers.rb:21:in `extract_and_validate_params'
    from /usr/local/rvm/gems/ruby-1.8.7-p334/gems/cassandra-0.11.4/lib/cassandra/cassandra.rb:433:in `insert'
    from cassandra:6
```

After that I tried your suggestion about gcc I've got this output:

I checked my gcc's version and it is 4.2 LLVM

```
$ gcc -v
Using built-in specs.
Target: i686-apple-darwin11
Configured with: /private/var/tmp/llvmgcc42/llvmgcc42-2335.15~25/src/configure --disable-checking --enable-werror --prefix=/Developer/usr/llvm-gcc-4.2 --mandir=/share/man --enable-languages=c,objc,c++,obj-c++ --program-prefix=llvm- --program-transform-name=/^[cg][^.-]*$/s/$/-4.2/ --with-slibdir=/usr/lib --build=i686-apple-darwin11 --enable-llvm=/private/var/tmp/llvmgcc42/llvmgcc42-2335.15~25/dst-llvmCore/Developer/usr/local --program-prefix=i686-apple-darwin11- --host=x86_64-apple-darwin11 --target=i686-apple-darwin11 --with-gxx-include-dir=/usr/include/c++/4.2.1
Thread model: posix
gcc version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)
```

I've used the `export CC=gcc-4.2` but it seems to do nothing. The rubygem error is just a matter while generating the docs.

```
$ rvm remove 1.9.2 && rvm install 1.9.2
Removing /usr/local/rvm/src/ruby-1.9.2-p180...
Removing /usr/local/rvm/rubies/ruby-1.9.2-p180...
Removing ruby-1.9.2-p180 aliases...
Removing ruby-1.9.2-p180 wrappers...
Removing ruby-1.9.2-p180 environments...
Removing ruby-1.9.2-p180 binaries...
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-1.9.2-p180, this may take a while depending on your cpu(s)...

ruby-1.9.2-p180 - #fetching 
ERROR: Error running 'bunzip2 '/usr/local/rvm/archives/ruby-1.9.2-p180.tar.bz2'', please read /usr/local/rvm/log/ruby-1.9.2-p180/extract.log
ruby-1.9.2-p180 - #extracting ruby-1.9.2-p180 to /usr/local/rvm/src/ruby-1.9.2-p180
ruby-1.9.2-p180 - #extracted to /usr/local/rvm/src/ruby-1.9.2-p180
Fetching yaml-0.1.3.tar.gz to /usr/local/rvm/archives
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  455k  100  455k    0     0  31664      0  0:00:14  0:00:14 --:--:-- 88696
Extracting yaml-0.1.3.tar.gz to /usr/local/rvm/src
Configuring yaml in /usr/local/rvm/src/yaml-0.1.3.
Compiling yaml in /usr/local/rvm/src/yaml-0.1.3.
Installing yaml to /usr/local/rvm/usr
ruby-1.9.2-p180 - #configuring 
ruby-1.9.2-p180 - #compiling 
ruby-1.9.2-p180 - #installing 
Removing old Rubygems files...
Installing rubygems dedicated to ruby-1.9.2-p180...
Installing rubygems for /usr/local/rvm/rubies/ruby-1.9.2-p180/bin/ruby
ERROR: Error running 'GEM_PATH="/usr/local/rvm/gems/ruby-1.9.2-p180:/usr/local/rvm/gems/ruby-1.9.2-p180@global:/usr/local/rvm/gems/ruby-1.9.2-p180:/usr/local/rvm/gems/ruby-1.9.2-p180@global" GEM_HOME="/usr/local/rvm/gems/ruby-1.9.2-p180" "/usr/local/rvm/rubies/ruby-1.9.2-p180/bin/ruby" "/usr/local/rvm/src/rubygems-1.6.2/setup.rb"', please read /usr/local/rvm/log/ruby-1.9.2-p180/rubygems.install.log
WARN: Installation of rubygems did not complete successfully.
ruby-1.9.2-p180 - adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
ruby-1.9.2-p180 - #importing default gemsets (/usr/local/rvm/gemsets/)
Install of ruby-1.9.2-p180 - #complete
```

I'll install a "real" gcc on my Mac and try this again.

**Comment by tomoyoirl** [comment] 2011-08-11 22:29
Hi. I'm on Lion, and had a version of Ruby compiled with gcc-llvm, and I ran into the same problem. I can confirm that, after recompiling it with gcc-4.2, the problem has gone away.

**Comment by rwjblue** [comment] 2011-08-12 03:29
Closing this issue, as it is definitely not an issue with this gem, but with ruby itself compiling under gcc-llvm.

**Closed as completed by rwjblue** 2011-08-12 03:29 UTC

**Comment by matthuhiggins** [comment] 2011-08-23 21:32
While the problem isn't caused by this gem, this is the only gem that shows the problem, and a google search shows this result first. In our case, we needed to use the full path to gcc-4.2:

```
export CC=/usr/bin/gcc-4.2
```

**Comment by adilsoncarvalho** [comment] 2011-08-23 23:52
I've done it. Removed and recompiled it using this gcc

`
i686-apple-darwin11-gcc-4.2.1
`

Now I get other problem when trying to run my simple code.

It throws

`
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/thrift-0.7.0/lib/thrift/protocol/binary_protocol.rb:111:in `write_string': undefined method `length' for 34:Fixnum (NoMethodError)
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/thrift-0.7.0/lib/thrift/client.rb:35:in `write'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/thrift-0.7.0/lib/thrift/client.rb:35:in `send_message'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/cassandra-0.12.1/vendor/0.8/gen-rb/cassandra.rb:247:in `send_batch_mutate'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/cassandra-0.12.1/vendor/0.8/gen-rb/cassandra.rb:242:in `batch_mutate'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/thrift_client-0.7.0/lib/thrift_client/abstract_thrift_client.rb:131:in `handled_proxy'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/thrift_client-0.7.0/lib/thrift_client/abstract_thrift_client.rb:60:in `batch_mutate'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/cassandra-0.12.1/lib/cassandra/protocol.rb:7:in `_mutate'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/cassandra-0.12.1/lib/cassandra/cassandra.rb:459:in `insert'
    from cassandra:6:in `<main>'
`

Will look in the issues to see if someone had this problem.

**Comment by ivmaykov** [comment] 2011-08-30 23:34
adilsoncarvalho: it looks like the underlying thrift library is trying to call write_string but is passing it a Fixnum. This may be a bug in Thrift itself, I'll investigate.

**Comment by technicool** [comment] 2011-09-01 23:35
FYI, I'm having the same problem on OS X 10.6.7, with the latest xcode and ruby version: ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-darwin10.7.0]

Is there any easy workarounds?

**Comment by rwjblue** [comment] 2011-09-01 23:54
Removing the current ruby and recompiling using GCC fixed the issue for most people.

If you are using RVM try something like:

```
export CC=gcc-4.2
rvm remove 1.9.2 && rvm install 1.9.2
```

**Comment by karmi** [comment] 2011-09-21 14:05
Note, that this issue also affects the HBase Thrift transport. You have to recompile Ruby as suggested.

**Comment by gerbdla** [comment] 2011-09-28 21:23
I am on mac os lion and I have tried all the steps above and I am not having any success.  
here is what I did

export CC=gcc-4.2
rvm install 1.9.2

get this error when performing a cassandra insert
Abort trap: 6

works fine in 1.8.7

is there a way I can determine that I am using the right compiler.  How does rvm know to use this?

**Comment by matthuhiggins** [comment] 2011-09-28 21:25
@gerbdia On Lion, I needed to use
  export CC=/usr/bin/gcc-4.2

**Comment by rwjblue** [comment] 2011-09-28 22:21
You may need to remove your 1.9.2 install first. You can do that with:

rvm remove 1.9.2

**Comment by carloscm** [comment] 2011-10-21 23:33
Not content with just downgrading/switching compilers I traced this to a bug in the thrift native extension:

https://issues.apache.org/jira/browse/THRIFT-1400

**Comment by rwjblue** [comment] 2011-10-22 00:09
Good job tracking that down. Thanks for updating us with your progress.

**Comment by gerbdla** [comment] 2011-12-18 23:50
Keith not sure I have moved on to new things since that you can post question at gihub

Thank You
David

**Comment by ivmaykov** [comment] 2011-12-19 05:08
Thrift-0.8.0 addresses the issue. There are some open pull requests to bump the thrift_client gem dependency to thrift-0.8.0 at which point this should work. Until there is a new release of thrift_client, you can download that gem, modify dependency to thrift-0.8.0 and install with 'rake install'.
